name: Build And Deploy

on: push

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        - name: ssh & clone project in VM
          uses: fifsky/ssh-action@master
          with:          
            host: ${{ secrets.HOST }}
            user: azureuser
            key: ${{ secrets.PRIVATE_KEY}}
            command: |
                git clone https://github.com/rishawsingh/deploy-to-vm.git 
                cd deploy-to-vm
                docker build . --file Dockerfile --tag node-docker:${{ github.sha }}
                docker run -d -p 8000:8000 node-docker:${{ github.sha }}
                curl --request POST \
                --url http://localhost:8000/test \
                --header 'content-type: application/json' \
                --data '{"msg": "testing"}'
                cd ..
                rm -r deploy-to-vm


